<h1>Python Basics</h1>
Not just another Python tutorial, focus is on using it for data science. Store and manipulate data, deploy tools for your own analysis. Python made by Guido van Rossum started as hobby project now it's a general purpose language you can make basically any kind of software with it, not that you should lol. Since Python is open source, the community made many data science packages so that it matches up to R, and is actually more popular now. Fancy visualizations, connecting to db for sensor measurement analysis, etc.
Version 2.7 is fading over time, use 3.x (latest was 3.5 for a while now on 3.7, most people on 3.5) .

Can do interactive sessions in IPython Jupyter, or write a python file ".py" .

In [1]:
#This is a Python comment
print(5/8) #print call
print(4 ** 2) #4^2, exponent
print(18%7) #modulo, gives remainder of int division
print(100*(1.1**7)) #annual cmpnded interest, A = P(1+r)^t

0.625
16
4
194.87171000000012


In [2]:
height = 2 #defining variable, remember variables in any programming lang are case-sensitive,
#so if you ask back value of "Height" get error since defined "height".

weight = 68.7 #5 main types number, string, tuple, list, dictionary. There's also boolean.
#Number can be float/int/long. In 2.7 Python doing 5/8 gives zero, because 8 goes into
#5 zero times, and the remainder is discarded. But doing 5.0/8.0 worked right. But after moving
#on from Python 2.x, this problem removed, any integer division converted to (& returns) float.

z = True #doing type(z) would say bool, a boolean is always either true or false.
type(weight) #will say float.

float

In [3]:
'ab'+'cd' #the + operator is overloaded, concats for string and math adds for number
#so different type, different behavior.
desc = "compound interest"
doubledesc = desc+desc #concatenates the given string with itself
print(doubledesc)

compound interestcompound interest


In [4]:
str(weight) #type conversion of that float to string
pi_string = "3.1415926"
pi_float = float(pi_string) #converts above to float
print("I said "+ ("Hey " *2) + "Hey!") #mult on string concats it with itself as many times
#as you say the 'multiplication' needs to occur, this will say 'I said Hey Hey Hey!'.

I said Hey Hey Hey!


<h1>Python Lists</h1>

In [5]:
heights = [1.73, 1.68, 1.71, 1.89] #this is a list, you wouldn't want to store a dataset of
#heights in separate variables that's a nightmare. List is an array.

collage = ["str", True, 1, 2.77] #a list can store diff types, elements can be lists also.
fam = ["appa", 2, "amma", 2] #rather than do this storing names every other elt, do below:

fam2 = [["appa", 2], ["amma", 2]] #version using sublists for each person. Now rather than
#using error prone system where even index is name (0,2,4) and odds are height (1,3,5) you
#instead have each family member's info together in own sublists.

print(fam[0]==fam2[0][0]) #both give "appa", but fam2 data structure better organized.
type(fam2) #list of lists itself must have type list, so do sublists.
#And never forget, indexing starts at zero :) .

True


list

In [6]:
list1 = [1+2,"a"*5, 3] #list of [3,"aaaaa", 3]
list1[-1] #negative indexing, starts after last elt of list & goes back (by 1 in this case),
#the last element is [-1]. DONT forget second index is still exclusive when using a negative 
#index. so if -1 is second index, so sublicing [:-1], get up to 2nd-to-last-element.

list1[1:2] #slice of a list, first index is the first element that will be in the slice, 
#but second index is exclusive, so it's not in the slice, slice goes up to element before the
#2nd index. So list1[1:2] says 2nd elt up to but not including 3rd elt, just gives "aaaaa".

#If you wanted the third elt also (index 2) then you CAN technically do list1[1:3] but that
#second index is technically out of bounds, so operation only works because the second index 
#is exclusive. The proper way is list1[1:], by not specifying second index it goes to end.

['aaaaa']

In [7]:
#Similarly list1[:2] gives start up to before index = 2 so [3, 'aaaaa']. And list1[:] goes 
#from start to end you'll get all three elements, the entirety of list1.
list1[:2]

[3, 'aaaaa']

In [8]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 
         9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

In [9]:
fam[3] = 2 #after making a list set a particular element.
fam2[-1][1] = 2 #doing the same for a list-within-list, update amma's height.
#Can also slice a list and replace with another list, updating multiple elts in 1 command.

x = ["a", "b", "c", "d"] #example of replacing slice of list with new list.
x[1] = "r"
x[2:] = ["s", "t"]

In [10]:
#If you use + operator with two lists, concatenates like with strings. Can't use plus
#to add an element to list, so areas = areas + "porch" or areas = areas + 2 gives error.
areas = areas + ["porch"] #how to actually do it.
del(areas[10]) #delete the element we just added.

Behind the scenes, if you declare a list x, it is stored in the memory, and x just has the address of where the list begins in memory. IMPORTANT when you copy a list like y=x, you copied the reference, and then changing y will also change x. To actually get a separate copy,  y = list(x) or y = x[:] will do the trick.

In [11]:
#Lets say areas is a list of 14, you want to delete the 11th and 12th element. You can 
#in one command say del(areas[-4:-2]) which deletes that slice of 11th and 12th.

<h1>Functions and Packages</h1>
A function is nothing but a piece of reuseable code that solves a particular task, takes in values and returns something after running the code with the values.

In [12]:
#type() is an example of a builtin function.
#max(areas) won't work, list must contain all same data type, so all numbers or all strings.

#the max function is also built in, returns maximum value in a list by doing > compare for
#all values in list until reaching end, setting max = any item if it's greater than max.

tallest = max([2,3,4])
print(round(8.94, 1)) #2nd argument is the precision. This also a built in. Not giving 2nd
#arg means number gets rounded to closest int.
help(round) #gives you documentation on the function, Shift+Tab in Jupyter also does this.

8.9
Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [13]:
#the bracket above around ndigits means it's optional, can do round(number, ndigits) or just
#round(number). If you need to do 'x' which is like a standard task, likely a built in exists.

print(len(areas)) #built in for list length, also can give amt of chars in a string.
#complex(real[, imag]) a built in for complex numbers.
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]
full = first+second #below line sorts this list in descending order.
sorted(full, reverse = True) #built in sorted(iterable, key=None, reverse=False). None and
#False are default values for those two params. iterable is any collection like list.

10


[20.0, 18.0, 11.25, 10.75, 9.5]

Built ins only one part of the story. methods are functions that are part of a class, they
belong to an object. Lists have methods like count, any list has it. Object is the base type, 
the five basic types str, list , number (subtypes are float, long, int which is what actually
shows up when you do type(value) and not Number) etc. inherit from object. All objects have 
methods so object/instance of class str has str methods, lists have list methods, float, etc. So diff types of objects all have methods depending on the type.

In [14]:
fam.index("amma") #list method to get index of a value's first occurence in a list.

fam.count(2) #list method to count amt times a value occurs in a list. You are calling 
#method count or index on fam which is an instance of class list (which has those methods).
me = "neeraj"
me = me.capitalize() #string method to capitalize first letter of a string object.
me = me.replace("j", "jakshi") #string method replaces first occurence of 1st arg in a string 
#with second arg.
me.index("jakshi") #index method exists on string also as does count. Some methods are in more
#than 1 type, method acts differently but analogously in each type. 

5

In [15]:
#For list, index gets index of first matching element in list, and for strings gets index
#of first time the substring is found as seen above substring doesn't have to be a single char.

fam.append("me") #list method that adds to end of list. Actually overwrites the list object 
#you call it on. Notice that capitalize string method did NOT overwrite, just returned a 
#modified copy.
me.count('a')
me.upper() #string method to uppercase, lower does lowercase.


'NEERAJAKSHI'

In [16]:
areas.index(9.5)
areas.count(9.50) #these two list methods don't change the list, but below three all do.
areas.append("porch") #similar to areas = areas + "porch"
areas.remove("porch") #remove first occurence of value. A delete(areas[10]), 11th elt, does
#same but using index.
areas.reverse() #reverses order of elts in list

In [17]:
areas

[9.5,
 'bathroom',
 10.75,
 'bedroom',
 20.0,
 'living room',
 18.0,
 'kitchen',
 11.25,
 'hallway']

Methods very powerful can use other people's code to solve your problem. But adding all python functions and methods anyone ever made into the python distribution would be huge mess, most code not being used. That's why there's packages that you "pip install". They are directory of Python scripts, each script is a module that defines some methods and types to solve particular problems. Thousands of packages like numpy for efficient array, matplotlib for data viz and scikit-learn for machine learning. You command line install using "pip install name" and then in a script "import name" at top.

In [18]:
import numpy #import installed package numpy
import numpy as np #alias so can do "np.bla" instead of "np.bla" everywhere.

np.array([1, 2, 3]) #just array([1,2,3]) would throw not defined error unless you did 
# from numpy import * , or from numpy import array.

from numpy import array as arrb #give alias when importing one piece, can't give alias when 
#you do "from numpy import *" (in that case imported to global scope, no np.array just array).

import matplotlib.pyplot as plt #other ways are from matplotlib import pyplot as plt or
#from matplotlib.pyplot import * if want all directly in namespace (hist instead of plt.hist)

#Best practice NOT to import * or to import members directly in. Best practice IS to import
#whole lib with/without alias so you know what functions/methods/types come from what package.

In [19]:
import math
from math import radians
C = math.pi*2*0.43
print("Circumf: "+str(C)) #have to explicit cast float Circumf to string for print out.

dist = 192500*radians(12) #distance travelled by Moon over 12 degrees of orbit. Can calc
#this as r * phi, r is radius phi is angle in radians. Radians fn converts 12 degrees to rad.

Circumf: 2.701769682087222


<h4>NumPy</h4>

In [20]:
#Lists can hold any type, diff types same time, change add remove elts, but missing way to do 
#any operation over entire collection and fast. 
heightList = [1.73, 1.68, 1.71, 1.89, 1.79]
weightList = [65.4, 59.2, 63.6, 88.4, 68.7]

#want to calc bmi = weight / (height^2). Can't directly do weight / height ** 2, throws error
#unsupp operand types for **: list & int. Could for loop over both lists but very inefficient.
npHeight = np.array(heightList)
npWeight = np.array(weightList)
bmi = npWeight / npHeight ** 2 #now have easy efficient way to do operation for entire set.
print(bmi) #Numpy behind the scenes calls all matrix operations in C that's why efficient.

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


Calculations for bmi were performed element-wise using both numpy arrays, dividing each elt
of npWeight by each element^2 from npHeight. Efficient elt-wise operations is why np array 
beats list. For this to be possible, np assumes each array only contains one type unlike list. After all, it must send the operation off to C so needs one type. If you try to use several types in np array, all coerced to strings. Try numpy array with 19 floats 1 string, all 20 will be strings. If instead combining ints and floats and booleans, all ints upcast to float, bool coerced to int then upcast to float. The np array is a created python type (numpy.ndarray, so class ndarray in package numpy), a type just like built in types like str, list, etc. Adding two lists concatenates. Adding two np arrays does elt-wise adding.

In [21]:
#Apart from above differences, np array shares many operations with list.
bmi[1] #gets 2nd item in bmi, just like doing list1[1].

bmi > 23 #returns bool np array same size as bmi, wwith each index "i" true if bmi[i]> 23. 

bmi[bmi > 23] #in numpy can use bool array to subset similar to slicing a list. Returns all 
#elts where that condition true. If assigned the bmi > 23 bool array to b, can do bmi[b].

x = np.array(["X", "X", "Y", "Z", "Z"])
y = np.array([4, 1, 10, 7, 9])

print(y[x == "Z"]) #bool array of which indices in x are "Z", used to select same indices in y.

[7 9]


In [22]:
#Could convert whole of npHeight to feet just doing npHeight*3.281, one line -> elt-wise.

np.array([True, 1, 2]) + np.array([3, 4, False]) #results in type coercion, true becomes 1.

array([4, 5, 2])

In [23]:
#The nd in ndarray means n dimensional; numpy array can be many dimensions.
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]]) 
#list of lists, sublists are just heightList and weightList from before.
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

TypeError data type not understood occurs when you try to pass the sublists directly, need the parent list otherwise python takes 1st sublist as the data, 2nd sublist as dtype arg. This makes it very clear why that error, the 2nd sublist is a list of data and not a dtype string!

In [24]:
#numpy rule applies for any nd array, 2d or more: ndarray can only contain 1 type. If one of 
#the 10 floats is changed to string, all elts will be coerced to string.
print(np_2d.shape)
print(np_2d[0]) #gives first row so first sublist, heightList.
print(np_2d[0][2]) #third element of first row.
print(np_2d[0,2]) #[row, col], gets 3rd elt of 1st row same as above.
np_2d[:,1:3] #get 2nd & 3rd persons' height AND weight. gets all (both) rows, 2nd&3rd cols. 
#could have done np_2d[0:,1:3] or even np_2d[0:2,1:3] but remember second way [0:2] improper.

(2, 5)
[1.73 1.68 1.71 1.89 1.79]
1.71
1.71


array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [25]:
np_2d[1,:] #second row all cols. gets all 5 people's weights.

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [26]:
np_2d[1] / np_2d[0] **2 #calc same bmi, weightList went into [1] and heightList into [0] .

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [27]:
baseball = [[74, 180], #height(in) weight(lb) are the cols, rows are samples (diff players)
            [74, 215],#this is how data should be organized. np_2d was backwards, height &
            [72, 210], #weight as rows, diff people as cols, if transpose that, get correct.
            [72, 210]]

np_baseball = np.array(baseball)
print(type(np_baseball)) #<class 'numpy.ndarray'>, just type(np_baseball) gives numpy.ndarray .
print(np_baseball.shape) #dimensions of the ndarray. Full size one in DataCamp is (1015,2) . 

#So that has all 1015 players' heights and weights, this example is 4 players.

<class 'numpy.ndarray'>
(4, 2)


In [28]:
print(np_baseball[2,:]) #print out 3rd row, 3rd player's height and weight.
print(np_baseball[:,1]) #entire second column, all 4 players' weights.
print(np_baseball[3,0]) #the 4th player's height. 

[ 72 210]
[180 215 210 210]
72


In [29]:
example = [[74, 180], 
          [74, 215]*3,
          [72, 210], 
          [72, 210]]
example = np.array(example)
print(example.shape) #not all rows have 2 cols (2nd row has 6), shape only shows rows.

example #still can row-col index example[3][0], but example[2,:] or example[:,1] gives error 
#too many indices, since col amt not uniform.

(4,)


array([list([74, 180]), list([74, 215, 74, 215, 74, 215]),
       list([72, 210]), list([72, 210])], dtype=object)

In [30]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat = np_mat * 2 #elt wise everything mult by 2
np_mat = np_mat + np.array([10, 10]) #if try to add diff shapes, numpy sees if possible to
#broadcast, here adding (3,2) w/ (1,2) same cols so adds the [10,10] elt-wise to each row.
np_mat

array([[12, 14],
       [16, 18],
       [20, 22]])

In [31]:
baseball2 = [[74.0, 180.0, 22.99], #new baseball list, height weight and age.
             [74.0, 215.0, 34.69],
             [72.0, 210.0, 30.78],
             [72.0, 210.0, 35.43],
             [73.0, 188.0, 35.71],
             [69.0, 176.0, 29.39]]
np_baseball2 = np.array(baseball2)
#in DataCamp example, next added "updated", also np.array, which elt-wise updated each 
#height, weight and age, since "updated" is to update by 1 year, all its age values were 1.

conversion = np.array([0.0254, 0.453592, 1]) #in to cm, lb to kg, age needs none.
print(np_baseball2*conversion)#not dot product (sum of elt-wise mult)! Just regular mult, each
#row mult with conversion, col to col no summing. Can alter whole data with little code!

[[ 1.8796   81.64656  22.99    ]
 [ 1.8796   97.52228  34.69    ]
 [ 1.8288   95.25432  30.78    ]
 [ 1.8288   95.25432  35.43    ]
 [ 1.8542   85.275296 35.71    ]
 [ 1.7526   79.832192 29.39    ]]


IF you did `np_baseball2.dot(conversion)` or `np.dot(np_baseball2,conversion)`, the dims are
1015,3 and 3,1 inner dims match leads to 1015,1. Here since it's NOT dot prod, and just reg multiplication, get 1015,3. For regular mult the col amount must match, and for dot prod inner dims must match (cols of left with rows of right). This means for regular mult, "conversion" array must be a horizontal row vector, and for dotprod "conversion" is vertical column vector. 
Ff conversion is array of not 3 elts (4 for example), mismatch errors for both reg-mult and dot-prod are below. 
```python
In [3]: np_baseball*conversion #regular mult
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    np_baseball*conversion
ValueError: operands could not be broadcast together with shapes (1015,3) (4,)

In [4]: np_baseball.dot(conversion) #dot prod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    np_baseball.dot(conversion)
ValueError: shapes (1015,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)
```

First step in analyzing data is getting to know data in first place. If dataset is small can just look at it, for big data need statistics. Aside from efficient data structure for number crunching, turns out NumPy also good at this stat work.

In [45]:
heightRandom = np.round(np.random.normal(1.75, 0.20, 5000), 2) #height(m)
#args for np.random.normal are (mean, stddev, num samples)

weightRandom = np.round(np.random.normal(60.32, 15, 5000), 2) #weight(kg)
#and then np.round used to round all elts of each array to 2 places.

np_city = np.column_stack((heightRandom, weightRandom)) #use those arrays as columns.

np.mean(np_city[:,0]) #all rows first col, finding mean of all samples' heights.
np.median(np_city[:,0]) #median is middle number when sorted, no need to sort function does.

#These summarizing stats give sanity check, if avg height is 2000, you know something's 
#wrong. Remember, mean heavily influenced by far outliers, median isn't.

1.755

In [47]:
print(np.std(np_city[:,0])) #standard deviation of height.

np.corrcoef(np_city[:,0], np_city[:,1]) #correlation coefficient, to see if height & weight 
#are correlated. The two non-one's show a tiny positive corr, aren't really that correlated.
#Normally height & weight have much higher corr like .5+, since both from randoms tiny corr.

0.20211049666951986


array([[1.        , 0.01032987],
       [0.01032987, 1.        ]])

What it truly says: 1st row for col1, so height 100% corr with itself and a tiny pos corr with col2. Then 2nd row for col2(weight) same tiny pos corr with col1(height) and 100% with itself. That's why one's are always on the diagonal, nth elt in nth row is for the nth col and any data always 100% correlation with itself obviously.

In [51]:
pl_positions = np.array(['K', 'M', 'A', 'D', 'M', 'D', 'GK', 'A']) #all players' positions.
pl_heights = np.array([191, 184, 185, 180, 181, 187, 191, 185]) #all players' heights.
#both same people in same order so can use bool index like below.

gk_heights = pl_heights[pl_positions == 'GK'] #use bool array where positions is GK to 
#index into heights, only get heights where same index in pl_positions is True(so is 'GK').

other_heights = pl_heights[pl_positions != 'GK'] #opposite of above, not GK bool indexing.

print(np.median(gk_heights)) #mean Goalkeeper height quite higher than avg of all others.
np.median(other_heights) #and that makes sense.

191.0


185.0